# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Computational Art Theory
paginate:       50
baseurl:        ""
url:            "https://isaac-art.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Isaac Clarke
  url:          http://ishimura.uk
  email:        isaac@ishimura.uk

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/isaac-art/isaac-art.github.io

# Gems
gems:
  - jekyll-paginate
